name: Homelab deploy github action
on:
  workflow_call:
    inputs:
      ssh-host:
        description: "SSH HOST"
        required: true
        type: string
      ssh-private-key:
        description: "SSH PRIVATE KEY"
        required: true
        type: string
      ssh-user:
        description: "SSH USER"
        required: true
        type: string

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ inputs.ssh-private-key }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ inputs.ssh-host }} >> ~/.ssh/known_hosts

      - name: Debug SSH
        run: |
          ssh -vvv sofien@${{ inputs.ssh-host }} ls -la
