name: Homelab deploy github action
on:
  workflow_call:
    inputs:
      ssh-user:
        description: "SSH USER"
        required: true
        type: string
    secrets:
      SSH_HOST:
        description: "SSH HOST"
        required: true
      SSH_PRIVATE_KEY:
        description: "SSH PRIVATE KEY"
        required: true



jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{  secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Debug SSH
        run: |
          ssh -vvv sofien@${{  secrets.SSH_HOST }} ls -la
